version: 1.0.{build}
before_build:
- ps: nuget restore ./BikeTrips.sln
build:
  project: ./BikeTrips.sln
  publish_nuget: true
  include_nuget_references: true
verbosity: minimal
environment:
COVERALLS_REPO_TOKEN:
	secure: 5w0Wp9I8Vuavjq0QdOMPHK1dw53S3O5Za05cuDO3TkKcBpGF/bSnk2eToS+CU/JC
after_test:
- packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"BikeTrips\packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:"/domain:single BikeTrips\Tests\BikeTrips.Services.Web.Tests\bin\Debug\ReadingClub.Services.Web.Tests.dll" -output:cover.xml
- packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover cover.xml