version: 1.0.{build}

before_build:
- cmd: nuget restore ./BikeTrips.sln

build:
  project: ./BikeTrips.sln
  publish_nuget: true
  include_nuget_references: true
verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: 5w0Wp9I8Vuavjq0QdOMPHK1dw53S3O5Za05cuDO3TkKcBpGF/bSnk2eToS+CU/JC
    
